// This file is auto-generated by Supabase CLI
// Run: npm run db:generate-types
//
// To generate types from your remote Supabase project:
// supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          display_name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      recipes: {
        Row: {
          id: string;
          user_id: string;
          youtube_video_id: string;
          title: string;
          description: string | null;
          thumbnail_url: string | null;
          channel_name: string | null;
          channel_id: string | null;
          ingredients: Json;
          instructions: Json;
          tags: string[];
          cuisine: string | null;
          cook_time_minutes: number | null;
          prep_time_minutes: number | null;
          servings: number | null;
          difficulty: "easy" | "medium" | "hard" | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          youtube_video_id: string;
          title: string;
          description?: string | null;
          thumbnail_url?: string | null;
          channel_name?: string | null;
          channel_id?: string | null;
          ingredients?: Json;
          instructions?: Json;
          tags?: string[];
          cuisine?: string | null;
          cook_time_minutes?: number | null;
          prep_time_minutes?: number | null;
          servings?: number | null;
          difficulty?: "easy" | "medium" | "hard" | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          youtube_video_id?: string;
          title?: string;
          description?: string | null;
          thumbnail_url?: string | null;
          channel_name?: string | null;
          channel_id?: string | null;
          ingredients?: Json;
          instructions?: Json;
          tags?: string[];
          cuisine?: string | null;
          cook_time_minutes?: number | null;
          prep_time_minutes?: number | null;
          servings?: number | null;
          difficulty?: "easy" | "medium" | "hard" | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          recipe_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          recipe_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          recipe_id?: string;
          created_at?: string;
        };
      };
    };
    Functions: {};
    Enums: {};
  };
}
