# Generated by Django 5.0.6 on 2026-06-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionjob',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload'), ('paste_transcript', 'Paste Transcript'), ('paste_text', 'Paste Text'), ('youtube_captions', 'Youtube Captions')], max_length=20),
        ),
    ]
