# Generated by Django 5.0.6 on 2026-06-29 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_extractionjob_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('fully_enriched', models.BooleanField(default=True)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fetched_at'], name='recipes_sea_fetched_e251d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('channel_id', models.CharField(blank=True, max_length=64)),
                ('channel_title', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(blank=True, null=True)),
                ('has_captions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='recipes_vid_updated_4b51af_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='recipes.searchquery')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='recipes.video')),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['query', 'rank'], name='recipes_sea_query_i_cf698e_idx')],
                'unique_together': {('query', 'video')},
            },
        ),
    ]
