# Generated by Django 5.0.6 on 2026-06-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_searchquery_video_searchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
