# Generated by Django 5.0.6 on 2026-06-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dietary',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('side', 'Side'), ('snack', 'Snack')], max_length=20),
        ),
    ]
