# Generated by Django 5.0.6 on 2026-07-01 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_backfill_recipe_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('channel_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.creator'),
        ),
    ]
