-- ============================================
-- DEPRECATED: Use migrations instead
-- ============================================
--
-- This file is kept for reference only.
-- Database schema is now managed via Supabase migrations.
--
-- See: apps/api/supabase/migrations/
--
-- To apply migrations to your Supabase project:
--
-- Option 1: Local development with Supabase CLI
--   npm run db:start      # Start local Supabase
--   npm run db:migrate    # Apply migrations
--
-- Option 2: Push to remote Supabase project
--   supabase link --project-ref YOUR_PROJECT_REF
--   supabase db push
--
-- Option 3: Manual (copy/paste migrations in order)
--   1. 20240101000000_initial_setup.sql
--   2. 20240101000001_create_profiles.sql
--   3. 20240101000002_create_recipes.sql
--   4. 20240101000003_create_favorites.sql
--
-- ============================================
